version: 2.1

parameters:
  pre-command:
    type: string
    default: "echo 'No pre-command'"
    description: "Command to run before the fix-flaky-tests command"
  post-command:
    type: string
    default: "echo 'No post-command'"
    description: "Command to run after the fix-flaky-tests command"
  max-tests:
    type: integer
    default: 3
    description: "The maximum number of tests to fix in a single run (defaults to 3)"
  max-prs:
    type: integer
    default: -1
    description: "The maximum number of PRs to open (-1 for unlimited, defaults to unlimited)"
  variations:
    type: integer
    default: 3
    description: "The number of fix variations to try in a single run (defaults to 1)"
  validations:
    type: integer
    default: 10
    description: "The number of test runs to validate the fix (defaults to 10)"
  no-output-timeout:
    type: string
    default: "30m"
    description: "The number of minutes to wait for output from the fix-flaky-tests command (defaults to 30m)"

executors:
  sandbox:
    machine:
      image: ubuntu-2404:current
    resource_class: large

commands:
  setup-sandbox:
    steps:
      - run:
          name: Setup sandbox
          command: |
            nvm install v22.15.1
            nvm alias default v22.15.1
      - run:
          name: "Configure node"
          command: |
            echo 'nvm use default' >> $BASH_ENV

jobs:
  fix-flaky-tests:
    executor: sandbox
    steps:
      - checkout
      - setup-sandbox
      - run:
          name: Pre-command
          command: << pipeline.parameters.pre-command >>
      - run:
          name: Fix flaky tests
          no_output_timeout: "<< pipeline.parameters.no-output-timeout >>"
          command: |
            npx -y @circleci/agents@canary fix-flaky-tests \
              --git-url << pipeline.project.git_url >> \
              --post-command "<< pipeline.parameters.post-command >>" \
              --max-tests << pipeline.parameters.max-tests >> \
              --max-prs << pipeline.parameters.max-prs >> \
              --variations << pipeline.parameters.variations >> \
              --validations << pipeline.parameters.validations >>
      - store_artifacts:
          path: /tmp/test-artifacts
          when: always
      - store_artifacts:
          path: flaky-tests-output
          when: always
      - store_artifacts:
          path: /tmp/logs/setup-environment.jsonl
          destination: setup-environment.jsonl
          when: always
      - store_artifacts:
          path: /tmp/logs/go-private-deps-discovery.jsonl
          destination: go-private-deps-discovery-log.jsonl
          when: always
      - run:
          name: Git ignore generated artifacts
          command: |
            echo "fix-flaky-tests-execution-output.json" >> .git/info/exclude
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  flaky-tests-fixer:
    jobs:
      - fix-flaky-tests:
          context:
            - circleci-agents
